### ISSUE TITLE
FFF data consolidation

### ISSUE THREAD

**Issue by jess-shue** [forestgeo/fgeo.misc#21]
Hi Mauro,
   Working on consolidating our new files from our recensus. I'm also having trouble with reprex, so including Markdown style code with a Dropbox link to two of the data files (let me know if that works!). I think right now the main issues are:  we aren't using 'tag' for a column name and after consolidating the worksheets into one workbook we can't combine them into one file as the xl_to_df function isn't found. We also need to add another sheet to the workbook to be consolidated with the rest:  secondary_recruits. This will function very much like the 'new_secondary_stems' sheet and the recruits page will have a  'New_Secondary' True/False column just like the 'original_stems' sheet.
Thanks!
Jess

    library(fgeo.tool)
    library(fgeo.base)
    library(reprex)
    library(fgeo.misc)

    devtools::install_github("forestgeo/fgeo.misc")
    
    files.directory <- "C:/Users/jessh/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output"
   
    files.export <- "C:/Users/jessh/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output/consolidated"
##### Create single worksheet from workbooks with multiple sheets
    fgeo.misc::xlff_to_xl(files.directory, files.export, first_census = FALSE)
    Error: Column `tag` not found in `.data`
    Call `rlang::last_error()` to see a backtrace
    In addition: Warning messages:
    1: Unknown or uninitialised column: 'new_stem'. 
    2: Length of logical index must be 1 or 64, not 0 
    3: `new_secondary_stems` has cero rows. 
    4: Filling every cero-row dataframe with NAs (new_secondary_stems). 

##### Compile the single sheet quadrat files into one file

    serc_test <- xl_to_df("C:/Users/jessh/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output/consolidated")
    Error in xl_to_df("C:/Users/jessh/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output/consolidated") : 
    could not find function "xl_to_df"

    library(writexl)

    write_xlsx(serc_test, "C:/Users/shuej/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output/consolidated_test.xlsx")

**Comment by maurolepore** [comment]
@jess-shue, 

I downloaded the data (and removed the link).

`xl_to_df()` does not exist in the package. Did it ever existed? I suspect that we don't need it. This will become clearer once I enable the `tag` column.

I was able to reproduce your error -- which is good news because it means I can now work towards fixing it. I'll be back  :)

**Comment by maurolepore** [comment]
Hi @jess-shue,

I may have fixed this. Please see [this report](https://github.com/forestgeo/fgeo.misc/blob/master/.buildignore/issue_21/issue_21.md#issue-21) and let me know what you think.

To try this yourself you'll need to reinstall fgeo.misc with 

```
devtools::install_github("forestgeo/fgeo.misc")
```

Let me konw if you need me to get online and walk you through the code.

Cheers,
M

**Comment by jess-shue** [comment]
Hi Mauro,
   Thank you for your continued help with this. I've followed some steps in your report (link you provided above), but I'm having trouble with the xlff_to_xl function. I would like to export the files separately to complete the vetting process. Once the vetting process is complete we would use the reduce function to have one, complete and clean file. However, trying the xlff_to_xl function is writing the files as .NA instead of .xlsx. Can I use xlff_to_xl to write multiple files to one location?
   Also, we would like to have the "Team" column from the root worksheet added to each stem similar to the date.
    devtools::install_github("forestgeo/fgeo.misc")
    library(fgeo.tool)
    library(fgeo.misc)

#### test with the files you previously downloaded from my other example; here are my paths

    files.directory <- "C:/Users/jessh/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output/raw"


    files.export <- "C:/Users/jessh/Dropbox (Smithsonian)/SERC_recensus_2019/FFF_output/consolidated"

    fgeo.misc::xlff_to_xl(files.directory, files.export, first_census = FALSE)


Thank you,
Jess

**Comment by maurolepore** [comment]
Hi @jess-shue,

Thanks for this. I fixed the extension problem and bumped the version number. Please reinstall fgeo.misc from GitHub as usual with `devtools::install_github("forestgeo/fgeo.misc")`.

``` r
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(fs)
  
  # install.packages("fgeo.tool")
  library(fgeo.tool)
  # devtools::install_github("forestgeo/fgeo.misc")
  library(fgeo.misc)
})

packageVersion("fgeo.tool")
#> [1] '1.2.4'
packageVersion("fgeo.misc")
#> [1] '0.0.0.9003'
```

> I would like to export the files separately to complete the vetting
> process … However, trying the xlff\_to\_xl function is writing the
> files as .NA instead of .xlsx.

Thanks\! The file extensions should now be correct. The problem is a bug
(I think) in the fs package (see <https://github.com/r-lib/fs/issues/205>).

(FYI, notice that the file extension is something you can change
manually. Just rename the file to give it the correct extension; then
the program associated to that extension should know how to open it.)

``` r
input <- here(".buildignore/issue_21/input")
dir_ls(input)
#> C:/Users/LeporeM/Documents/Dropbox/git/fgeo.misc/.buildignore/issue_21/input/15106_13112019-05-02_AS_t.xlsx
#> C:/Users/LeporeM/Documents/Dropbox/git/fgeo.misc/.buildignore/issue_21/input/15712019-05-10MS_t.xlsx

output <- here(".buildignore/issue_21/output")
xlff_to_csv(input, output, first_census = FALSE)
#> Warning: Unknown or uninitialised column: 'new_stem'.
#> Warning: Length of logical index must be 1 or 64, not 0
#> Warning: `new_secondary_stems` has cero rows.
#> Warning: Filling every cero-row dataframe with NAs (new_secondary_stems).
#> Warning: Unknown or uninitialised column: 'new_stem'.
#> Warning: Length of logical index must be 1 or 33, not 0
#> Warning: `new_secondary_stems` has cero rows.
#> Warning: Filling every cero-row dataframe with NAs (new_secondary_stems).

dir_ls(output)
#> C:/Users/LeporeM/Documents/Dropbox/git/fgeo.misc/.buildignore/issue_21/output/15106_13112019-05-02_AS_t.csv
#> C:/Users/LeporeM/Documents/Dropbox/git/fgeo.misc/.buildignore/issue_21/output/15712019-05-10MS_t.csv
#> C:/Users/LeporeM/Documents/Dropbox/git/fgeo.misc/.buildignore/issue_21/output/single_dataframe.csv
```

> Can I use xlff\_to\_xl to write multiple files to one location?

Yes, as shown above.

> Also, we would like to have the “Team” column from the root worksheet
> added to each stem similar to the date.

Okay (see <https://github.com/forestgeo/fgeo.misc/issues/22>)
